### ISSUE TITLE
Multiple where clause in Laravel 5.3

### ISSUE THREAD

**Issue by i2507** [uepg/laravel-sybase#28]
Hi, thanks for such convenient package. I have a question, could we use multiple where clause? In Laravel doc, we can
```
$query->where([
    ['column_1', '=', 'value_1'],
    ['column_2', '<>', 'value_2'],
    [COLUMN, OPERATOR, VALUE],
    ...
])
```
But when I tried to do the same thing, it came out the error. Please correct me if I have wrong using, thanks!

**Comment by mainginski** [comment]
All you can do with standard Eloquent, you, in theory could do with laravel-sybase, the package works as a translator. Can you transcribe the errors?

**Comment by i2507** [comment]
OK, it's wired. The code is as below:
```
$lists = Filght::where([['flight_name', '=', 'aaa'], ['no', '=', '0163']])->get();
```
then, the erros is:
```
QueryException in Connection.php line 769:
Undefined variable: new_binds (SQL: select * from [flights] where ([flight_name] = aaa and [no] = 0163))
```
any solution?

**Comment by mainginski** [comment]
i'll check!

**Comment by galangnra** [comment]
did you tried it using orWhere ?
and the Code will be like this :
`$lists = Filght::where('flight_name', '=', 'aaa')
                        ->orWhere('no', '=', '0163')
                        ->get();`

**Comment by mainginski** [comment]
This will work, however, it needs to be fixed this implementation of Laravel 5.3.

**Comment by i2507** [comment]
@galangnra It works, and the code like this works too : 
`$lists = Filght::where('flight_name', '=', 'aaa')->Where('no', '=', '0163') ->get();`

but, what i want is to dynamically get user's input to generate where sql statement, that is why i want to define an array could store multiple where clauses, like:

```
$stat = [
    ['column_1', '=', 'value_1'],
    ['column_2', '<>', 'value_2'],
    [COLUMN, OPERATOR, VALUE],
    ...
]
```

**Comment by mainginski** [comment]
This should work, but I'll do some more testing.
