### ISSUE TITLE
Error while connecting to sybase database

### ISSUE THREAD

**Issue by SebastianBotez** [uepg/laravel-sybase#38]
When I try to connect to sybase DB I get this error: could not find driver.
Any ideea whats going on? My configuration is:

```
        'sybaseuepg-aluno' => [
            'driver'   => 'sqlsrv',
            'host'     => env('DB_HOST', 'host'),
            'port'     => env('DB_PORT', '35355'),
            'database' => env('DB_DATABASE', 'mydatabase'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', 'secret'),
            'charset'  => 'utf8',
            'prefix'   => '',
        ],
```

<img width="1427" alt="screen shot 2018-05-15 at 6 43 19 pm" src="https://user-images.githubusercontent.com/10911720/40067878-e578b512-586f-11e8-85a3-9c9547850aae.png">

**Comment by nunomazer** [comment]
Hi, you must install php sybase extension
