### ISSUE TITLE
Impossibility to use alias in tables, only in columns

### ISSUE THREAD

**Issue by mainginski** [uepg/laravel-sybase#4]
**Allowed**:
`SELECT column_name AS alias_name
FROM table_name;`

**Unallowed**:
`SELECT column_name(s)
FROM table_name AS alias_name;`

**Comment by nunomazer** [comment]
Try to not use 

     SELECT column_name(s) FROM table_name AS alias_name;

but at FROM clause only a space from the real name to the alias:

    SELECT column_name(s) FROM table_name alias_name;

**Comment by mainginski** [comment]
Remains the same, because the main issue is that when I relate the field with the alias, it will not relate to the table, because not yet implemented the recognition of aliases.
