### ISSUE TITLE
Ubuntu 18 laravel Sybase

### ISSUE THREAD

**Issue by Cons28** [uepg/laravel-sybase#62]
## Describe the bug
I cant use this package, i install and make the changes but dont work with sybase base, 
when i try use the next instruction : DB::select("SELECT GETDATE") i recive the next error 

Illuminate/Database/QueryException with message 'SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection because an error was encountered during handshakes before login. Common causes include client attempting to connect to an unsupported version of SQL Server, server too busy to accept new connections or a resource limitation (memory or maximum allowed connections) on the server. (SQL: SELECT GETDATE)'

please i need help

**Comment by nunomazer** [comment]
Hi @Cons28 

sorry but this package is not prepared/tested to be used with ODBC, we only support DBLIB  for now.

**Comment by Cons28** [comment]
Ok thanks for your answer i apreciate that, i need conect my laravel app
with sybase but i dont conect, my server app us ubuntu 18 for use this
package please tell me what is the server app configuration and ther server
database configuration.

**Comment by Cons28** [comment]
Thanks for the answer, i didnt have configuration in my server DBLIB, but now i have this configuration and work with this package.
Thanks.
