### ISSUE TITLE
I work with Laravel 6.x, Models dosnt work.

### ISSUE THREAD

**Issue by Cons28** [uepg/laravel-sybase#63]
Hello i work with this package, the conection is fine, but the models dosnt work. i try to use a USER Model but when i create a new user the project show this error : 

SQLSTATE[HY000]: General error: 20018 SQL Anywhere Error -852: Table name 'syscolumns' is ambiguous [20018] (severity 16) [ SELECT a.name, st.name AS type FROM syscolumns a, systypes b, systypes s, systypes st WHERE a.usertype = b.usertype AND s.usertype = a.usertype AND s.type = st.type AND st.name NOT IN ( 'timestamp', 'sysname', 'longsysname', 'nchar', 'nvarchar' ) AND st.usertype < 100 AND object_name (a.id) = 'users'] (SQL: select count(*) as aggregate from [users] where [email] = jhon@coofe.com)

**Comment by nunomazer** [comment]
Hi @Cons28, can you try it with a Laravel 5.8 version? And see if the error persist? I'll only have some time to work on this package at feb/2020 because of holidays

**Comment by Cons28** [comment]
Hello i try with a laravel 5.8 and the error persist :

SQLSTATE[HY000]: General error: 20018 SQL Anywhere Error -852: Table name 'syscolumns' is ambiguous [20018] (severity 16) [ SELECT a.name, st.name AS type FROM syscolumns a, systypes b, systypes s, systypes st WHERE a.usertype = b.usertype AND s.usertype = a.usertype AND s.type = st.type AND st.name NOT IN ( 'timestamp', 'sysname', 'longsysname', 'nchar', 'nvarchar' ) AND st.usertype < 100 AND object_name (a.id) = 'users'] (SQL: select count(*) as aggregate from [users] where [email] = jhon@coofe.com)

**Comment by mainginski** [comment]
@Cons28 Try use `yourdatabase..tablename` in `$table` variable on Model.

**Comment by nunomazer** [comment]
Closing since no feedback was given by @Cons28
