### ISSUE TITLE
This package is not working with latest php version 8.0.2

### ISSUE THREAD

**Issue by vmeditab** [uepg/laravel-sybase#73]
**My composer.json file:**

` "require": {
        "php": "8.0.2",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.29.0",
        "laravel/tinker": "^2.5",
        "uepg/laravel-sybase": "^2.1"
    },`

and when applying `composer update` this gives me below error

>  Problem 1
    - Root composer.json requires php 8.0.2 but your php version (8.0.1) does not satisfy that requirement.
  Problem 2
    - uepg/laravel-sybase[2.1.0, ..., 2.1.2] require laravel/framework 5.* -> found laravel/framework[v5.0.0, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^8.29.0).
    - uepg/laravel-sybase[2.2, ..., 2.4.0] require php ^5.6.4 || ^7.0 -> your php version (8.0.1) does not satisfy that requirement.
    - Root composer.json requires uepg/laravel-sybase ^2.1 -> satisfiable by uepg/laravel-sybase[2.1.0, ..., 2.4.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by nunomazer** [comment]
Hi @vmeditab 

but this line of error says your PHP version is 8.0.1 and in your composer you are asking for PHP 8.0.2

`Root composer.json requires php 8.0.2 but your php version (8.0.1) does not satisfy that requirement.`

So you need to update the PHP version of your environment before 

This not seems to be an error of this package.

**Comment by vmeditab** [comment]
Hello @nunomazer ... Thanks for the reply. I tried which you suggested. Please review my code and response. I am still getting errors.

**composer.json**

`"require": {
        "php": "8.0.1",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "8.29.*",
        "laravel/tinker": "^2.5",
        "uepg/laravel-sybase": "dev-master"
    },`

and after applying the command `composer update`, getting below error...

> Problem 1
    - Root composer.json requires uepg/laravel-sybase dev-master -> satisfiable by uepg/laravel-sybase[dev-master].
    - uepg/laravel-sybase dev-master requires php ^5.6.4 || ^7.0 -> your php version (8.0.1) does not satisfy that requirement.
