### ISSUE TITLE
this package not working with php 8

### ISSUE THREAD

**Issue by vmeditab** [uepg/laravel-sybase#74]
Please give an update for PHP 8 because this package does not work with it. Please verify my code.

**composer.json**

`  "require": {
        "php": "8.0.1",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "8.29.*",
        "laravel/tinker": "^2.5",
        "uepg/laravel-sybase": "dev-master"
    },`

Below getting an error while applying command `composer update` via terminal.

>  Problem 1
    - Root composer.json requires uepg/laravel-sybase dev-master -> satisfiable by uepg/laravel-sybase[dev-master].
    - uepg/laravel-sybase dev-master requires php ^5.6.4 || ^7.0 -> your php version (8.0.1) does not satisfy that requirement.

**Comment by nunomazer** [comment]
Hi @vmeditab, I updated the composer to accpet PHP 8.x environments
